### PR TITLE
FEAT: Add Auth Management

### PR DESCRIPTION
**Pull request by VishalPatil18**
### 📝 Description

The user can now log in and signup. One can also log in using guest credentials which could be applied with a click on `Guest Login` Button.

### 🚀 New behavior

- Add Auth provider and services using context and useReducer.
- The user can log in, signup, and log out.
- Add a guest Login credential.
- Update the color of greeting card #3
- Add Modal Component, LoginModal and LogoutModal components.
- Add `componentsContext` which would have state for all generic components like modal, alerts, toasts and loaders.

### 🖼 Preview Link

[https://vistream-react-version-gal94ftit-vishalpatil18.vercel.app/](https://vistream-react-version-gal94ftit-vishalpatil18.vercel.app/)

### 💣 Is this a breaking change?
- [ ] Yes
- [x] No

### 🔬 Is the code self-reviewed?
- [x] Yes
- [ ] No

### 📋 Is the code well-formatted?
- [x] Yes
- [ ] No

### 🔗 Related to Issue 
- #3  
- #5  

> NOTE: The site is not responsive yet. I will work on responsiveness at the end.

### CODE REVIEW

**Comment by RakshaPawar108** [comment]
Great Work Vishal!

**Review by RakshaPawar108 — APPROVED** [review]

**Comment by kart-c** [comment]
When a user navigates from other pages to settings/clicks on the user, the active state is still on the old tab

**Review by kart-c — APPROVED** [review]
The functionality works fine @VishalPatil18 Just a suggestion, I can signup using a blank email and password. A required attribute would be great

**Comment by VishalPatil18** [comment]
> The functionality works fine @VishalPatil18 Just a suggestion, I can signup using a blank email and password. A required attribute would be great

These checks would be done at the end for all input files all together.

>  When a user navigates from other pages to settings/clicks on the user, the active state is still on the old tab

Thanks for pointing it out. I will look into this.

**Comment by VishalPatil18** [comment]
>  When a user navigates from other pages to settings/clicks on the user, the active state is still on the old tab

I've created [an Issue](https://github.com/VishalPatil18/vistream-react-version/issues/7) #7 for this as of now. Will look into this later.

**Pull request merged**
