### PR TITLE
FEAT: Add history management

### PR DESCRIPTION
**Pull request by VishalPatil18**
### 📝 Description

A history page is where the user can see all the history of videos that they have watched.

### 🚀 New behavior

- Any video that the user watches gets added to the history
- History is visible from the history page
- User can remove one video from history
- User can also clear the whole history at once

### 🖼 Preview Link

[https://vistream-react-version-9o9w8536m-vishalpatil18.vercel.app/](https://vistream-react-version-9o9w8536m-vishalpatil18.vercel.app/)

### 💣 Is this a breaking change?
- [ ] Yes
- [x] No

### 🔬 Is the code self-reviewed?
- [x] Yes
- [ ] No

### 📋 Is the code well-formatted?
- [x] Yes
- [ ] No

### 🔗 Related to Issue
- #15 

> NOTE: The site is not responsive yet. I will work on responsiveness at the end.

### CODE REVIEW

**Review by Kevin-Solomon — APPROVED** [review]

**Review by kart-c — APPROVED** [review]
@VishalPatil18 fetch the history and likes again when a user logs back in. Data should persist unless the user refreshes the page

**Comment by kart-c** [comment]
On the single product page, give a fixed/max-width to the video description, as you can see it's pushing the other section.

**Comment by VishalPatil18** [comment]
> @VishalPatil18 fetch the history and likes again when a user logs back in. Data should persist unless the user refreshes the page

Ok, thanks for pointing it out. I'll fix this.

**Comment by VishalPatil18** [comment]
> 
> 
> On the single product page, give a fixed/max-width to the video description, as you can see it's pushing the other section.

@kart-c fixed all the bugs suggested!

**Comment by kart-c** [comment]
@VishalPatil18 looks good. Data for users is persisting now

**Pull request merged**
