### PR TITLE
FEAT: Add likes Management

### PR DESCRIPTION
**Pull request by VishalPatil18**
### 📝 Description

Like management is to manage the videos liked by any user.

### 🚀 New behavior

- Fetch the Liked videos from the backend
- Like new videos
- Remove the video from the liked section.
- Users can only like a video if they are logged-in

### 🖼 Preview Link

[https://vistream-react-version-nk1yonu2q-vishalpatil18.vercel.app/](https://vistream-react-version-nk1yonu2q-vishalpatil18.vercel.app/)

### 💣 Is this a breaking change?
- [ ] Yes
- [x] No

### 🔬 Is the code self-reviewed?
- [x] Yes
- [ ] No

### 📋 Is the code well-formatted?
- [x] Yes
- [ ] No

### 🔗 Related to Issue
- #10 

> NOTE: The site is not responsive yet. I would work on responsiveness at the end.

### CODE REVIEW

**Comment by kart-c** [comment]
Like status is not getting removed even after logging out, from both home and like pages

**Comment by AtulPant2704** [comment]
When user logouts, you are navigating him to the Home screen but active class in tabs is getting added to last tab in which I was present. You can see the video here for reference:- https://www.awesomescreenshot.com/video/8023973?key=a5f6099363d410f32eecd81958c12023

**Comment by VishalPatil18** [comment]
> When user logouts, you are navigating him to the Home screen but active class in tabs is getting added to last tab in which I was present. You can see the video here for reference:- https://www.awesomescreenshot.com/video/8023973?key=a5f6099363d410f32eecd81958c12023

This bug was pointed out by @kart-c. I've created [this](https://github.com/VishalPatil18/vistream-react-version/issues/7)  #7 issue. I will work on it later.

**Comment by kart-c** [comment]
If I login from user1 and like a few videos, I can see the videos in the liked sections. But now if I login from another user, user2, I can still see the liked videos of the user1. Can you fix this?

**Review by Kevin-Solomon — APPROVED** [review]

**Comment by VishalPatil18** [comment]
> If I login from user1 and like a few videos, I can see the videos in the liked sections. But now if I login from another user, user2, I can still see the liked videos of the user1. Can you fix this?

Thanks for pointing it out. I have created [an issue](https://github.com/VishalPatil18/vistream-react-version/issues/12) #12  for the same. Will work on this later.

**Review by kart-c — APPROVED** [review]

**Comment by VishalPatil18** [comment]
>  Like status is not getting removed even after logging out, from both home and like pages

Private routing is yet to be implemented. It would be done very soon.

**Pull request merged**
