### PR TITLE
FIX: Drawer active state bug fixed, createPlaylist Button on drawer fixed

### PR DESCRIPTION
**Pull request by VishalPatil18**
### 📝 Description

Drawer active state bug fixed.

### 🚀 New behavior

- The drawer tab now updates based on current page active
- The user can now create playlist from the `+create playlist` button on drawer at bottom

### 🖼 Preview Link

[https://vistream-react-version-owenprxph-vishalpatil18.vercel.app/](https://vistream-react-version-owenprxph-vishalpatil18.vercel.app/)

### 💣 Is this a breaking change?
- [ ] Yes
- [x] No

### 🔬 Is the code self-reviewed?
- [x] Yes
- [ ] No

### 📋 Is the code well-formatted?
- [x] Yes
- [ ] No

### 🔗 Related to Issue 
- #7

### CODE REVIEW

**Review by AtulPant2704 — APPROVED** [review]
Everything is good, tab switching is working fine now. Just one suggestion though, when user accesses private routes in log out, you display him an alert but you can open the login modal for him after that as you are doing in Create Playlist button. Here is the video for reference:-
https://www.awesomescreenshot.com/video/8075478?key=64bce7bfdb5414b1b8f67ce77e92bd73

**Comment by VishalPatil18** [comment]
> Everything is good, tab switching is working fine now. Just one suggestion though, when user accesses private routes in log out, you display him an alert but you can open the login modal for him after that as you are doing in Create Playlist button. Here is the video for reference:- https://www.awesomescreenshot.com/video/8075478?key=64bce7bfdb5414b1b8f67ce77e92bd73

Sure will work on this. Thanks for pointing out. 👍

**Review by RahullRawat — APPROVED** [review]
Good work @VishalPatil18

**Comment by Jay-Gadhiya** [comment]
- ui looks good
- drawer working fine
- create and delete playlist is working fine

**Review by Jay-Gadhiya — APPROVED** [review]

**Comment by VishalPatil18** [comment]
> Everything is good, tab switching is working fine now. Just one suggestion though, when user accesses private routes in log out, you display him an alert but you can open the login modal for him after that as you are doing in Create Playlist button. Here is the video for reference:- https://www.awesomescreenshot.com/video/8075478?key=64bce7bfdb5414b1b8f67ce77e92bd73

Created an [Issue](https://github.com/VishalPatil18/vistream-react-version/issues/21) #21  for the same as of now. I will work on this later.

**Pull request merged**
